# Generated by Django 3.1.3 on 2020-11-26 01:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodyweight',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bodyweight',
            name='weight',
            field=models.IntegerField(default=22),
            preserve_default=False,
        ),
    ]
